"""initial schema

Revision ID: 1cf780a74a82
Revises: 
Create Date: 2026-06-22 21:28:24.950734
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1cf780a74a82'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_project_id'), ['project_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('deal_type', sa.String(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('procore_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wbs', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('late_start', sa.Date(), nullable=True),
    sa.Column('late_finish', sa.Date(), nullable=True),
    sa.Column('total_float', sa.Integer(), nullable=True),
    sa.Column('free_float', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('procore_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'wbs', name='uq_task_project_wbs')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.Column('successor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.CheckConstraint('predecessor_id != successor_id', name='ck_dependency_no_self'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_dependency_pred_succ')
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependencies_predecessor_id'), ['predecessor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependencies_successor_id'), ['successor_id'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_task_id'), ['task_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_task_id'))

    op.drop_table('resources')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_task_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencies_successor_id'))
        batch_op.drop_index(batch_op.f('ix_dependencies_predecessor_id'))

    op.drop_table('dependencies')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('projects')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_project_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
